version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres_mvc_security:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: usersDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@55w0rd
    volumes:
      - postgres_data_mvc:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  postgres_secret_provider:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@55w0rd
      POSTGRES_DB: secret_providers_usersDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_secret:/var/lib/postgresql/data

volumes:
  postgres_data_mvc:
  postgres_data_secret:
  redis-data: